### ISSUE TITLE
selection colours

### ISSUE THREAD

**Issue by sledziu32** [hbisneto/excel-theme#1]
Hi,
May I sugest to change colours of selections?
![image](https://user-images.githubusercontent.com/19429371/175518972-b42bbc03-10eb-400d-8c8e-501df8cbb255.png)
I have selected 'utilis' in '<Directory "C:/utils/">' row but far more highlited is word from row above. 

Thanks in advance
Przemysław Zawadzki

**Comment by hbisneto** [comment]
> Hi, May I sugest to change colours of selections? ![image](https://user-images.githubusercontent.com/19429371/175518972-b42bbc03-10eb-400d-8c8e-501df8cbb255.png) I have selected 'utilis' in '<Directory "C:/utils/">' row but far more highlited is word from row above.
> 
> Thanks in advance Przemysław Zawadzki

Hi, Przemysław Zawadzki.
Thank you for your sugestion. Highlights will be improved as soon as possible in a future update. Stay tuned for news in MarketPlace.

Heitor Bisneto

**Comment by hbisneto** [comment]
Selection colours updated. Download Excel Theme 1.0.1 release: https://github.com/hbisneto/excel-theme/releases/tag/v1.0.1
