### ISSUE TITLE
Por favor, adicione isso em https://open-vsx.org/

### ISSUE THREAD

**Issue by torculus** [hbisneto/excel-theme#2]
Thank you for making this theme! It is very beautiful

Right now, it is only available on the VScode marketplace. This means that anyone using VSCodium or other open-source versions of VScode cannot download it

Would you please add this theme on the Open VSX marketplace [https://open-vsx.org/](https://open-vsx.org/) too?

Thank you!

**Comment by hbisneto** [comment]
That's a good task. I would like to support all of them, including Azure Data Studio.
I'll upload the files as soon as possible. Thank you!

**Comment by hbisneto** [comment]
@torculus,

The extensions were added to VSX Org.
You can download Excel Theme in this link: https://open-vsx.org/extension/BisnetoInc/theme-excel
